### ISSUE TITLE
Traefik2 services not using wildcard certificate correctly

### ISSUE THREAD

**Issue by appletalk** [htpcBeginner/docker-traefik#15] opened 2020-03-30 02:57 UTC
I noticed when trying to use your traefik 2 docker-compose file with cloudflare for a wildcard certificate, it would also try to generate a certificate for the service.example.com subdomain name(s).
It would appear in the acme.json and also I noticed TXT records would show up in the cloudflare DNS portal for the subdomains.

As per this guide the following line should be removed from each of the services to force them to use the wildcard cert.
`- "traefik.http.routers.service.tls.certresolver=cloudflare"`

https://medium.com/@containeroo/traefik-2-0-wildcard-lets-encrypt-certificates-1658370adc68

I'm not sure if this will cause other side effects, i'm quite new to all this :)
But at first glance it appears to work correctly with the removed line

**Comment by adradloff** [comment] 2020-03-30 17:57
Interesting, You are correct.  I didn't notice my config wasn't using the wildcard.  Thanks!

**Comment by htpcBeginner** [comment] 2020-04-01 21:36
Thanks for pointing out. I am making my move to T2. I will test and fix this.

**Comment by Akruidenberg** [comment] 2020-04-19 13:23
I have this problem also. I only wants a root and wilcard domain. But Traefik is generating a cert for every subdomain. How to fix this?

**Comment by robflate** [comment] 2020-04-19 13:46
What worked for me was to remove the certresolver lines from everything except Traefik. Clear acme.json (you may need to delete and remake it). Run Traefik. You should get a domain and a wildcard cert. Once done, comment out the certresolver line in Traefik. 

Consider using the Staging server to avoid hitting limits while testing.

**Comment by Akruidenberg** [comment] 2020-04-19 13:55
> What worked for me was to remove the certresolver lines from everything except Traefik. Clear acme.json (you may need to delete and remake it). Run Traefik. You should get a domain and a wildcard cert. Once done, comment out the certresolver line in Traefik.
> 
> Consider using the Staging server to avoid hitting limits while testing.

Will Traefik renew my certs with this method?

**Comment by robflate** [comment] 2020-04-19 14:02
Good question. I’d like to know the answer to that too.

**Comment by adradloff** [comment] 2020-04-19 14:32
yes Traefik will pull good and valid certs fro you domain.  I have done this method many times in a single day and over the course of a few days.

**Comment by Zwordi** [comment] 2020-05-01 20:10
I can confirm also that Traefik is self-managing the certificatie renewal.
You will receive mail from Letsencrypt is you do not use a certification until his renewal.

**Comment by htpcBeginner** [comment] 2020-05-11 17:33
Closing this as not much activity and I believe the problem is addressed.

**Closed by htpcBeginner** 2020-05-11 17:33 UTC
